# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: gitpod/workspace-full:latest

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - init: npm install &&
          gp sync-done installation  
         
  - init: gp sync-await installation &&
          npx playwright install &&
          gp sync-done playwrightInstallation
  
  - init: gp sync-await playwrightInstallation &&
          npx playwright install-deps &&
          gp sync-done playwrightBrowserDep

  - init: gp sync-await playwrightBrowserDep &&
          npx playwright test


# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 9323 for the frontend
    port: 9323
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
